# Configure for Red Hat corporate ID
- name: Store SSSD cache in tmpfs
  mount:
    path:  /var/lib/sss/db/
    src: tmpfs
    fstype: tmpfs
    opts: size=300M,mode=0700,noauto,rootcontext=system_u:object_r:sssd_var_lib_t:s0
    state: present
  notify: Remount sssd cache directory

- name: Fetch authconfig info
  command: authconfig --test
  register: ac_result1
  changed_when: false

- name: Install krb5.conf
  template: src="krb5.conf.j2" dest="/etc/krb5.conf" mode="644" owner="root" group="root"

- name: Install sssd.conf
  template: src="sssd.conf.j2" dest="/etc/sssd/sssd.conf" mode="600" owner="root" group="root"
  notify: Reload sssd

- name: Enable SSSD authentication
  command: authconfig --enablesssdauth --enablesssd --enablemkhomedir --update
  changed_when: false

- name: Fetch authconfig info
  command: authconfig --test
  register: ac_result2
  changed_when: ac_result1.stdout != ac_result2.stdout
  notify: Reload sssd
