
- name: Remount sssd cache directory
  mount:
    path:  /var/lib/sss/db/
    src: tmpfs
    fstype: tmpfs
    opts: size=300M,mode=0700,noauto,rootcontext=system_u:object_r:sssd_var_lib_t:s0
    state: mounted
  notify: Reload sssd

- name: Reload sssd
  service: name="sssd" state="restarted"
